package com.devwork.pro1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Money implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Money() {
    }




}