package com.devwork.pro1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Money implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String country;
	private java.lang.String unit;
	private java.math.BigInteger value;

	private java.lang.String comments;

	public Money() {
		System.out.println(""abcd");
	}

	public java.lang.String getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.String getUnit() {
		return this.unit;
	}

	public void setUnit(java.lang.String unit) {
		this.unit = unit;
	}

	public java.math.BigInteger getValue() {
		return this.value;
	}

	public void setValue(java.math.BigInteger value) {
		this.value = value;
	}

	public java.lang.String getComments() {
		return this.comments;
	}

	public void setComments(java.lang.String comments) {
		this.comments = comments;
	}

	public Money(java.lang.String country, java.lang.String unit,
			java.math.BigInteger value, java.lang.String comments) {
		this.country = country;
		this.unit = unit;
		this.value = value;
		this.comments = comments;
	}

}
